---
title: "文本挖掘"
date: ""
output:
  rmdformats::readthedown:
    highlight: kate
    number_sections: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(showtextdb)
library(showtext)
font_add(family = "songti", 
         regular = "C:/Windows/Fonts/simsun.ttc")
showtext_auto(enable=T)
opts_chunk$set(message=FALSE,
               warning=FALSE)
```


# 预处理

```{r}
library(jiebaR)
library(stringr)
data=read.csv('./和讯网滚动新闻-2.csv',header=TRUE,fileEncoding = 'gbk')
contents=data$content

## 将文本中所有的数字替换为""
contents <- str_replace_all(contents,"[0-9]","")
###分词
#添加自定义词典
#注意到新闻中存在公司名称，从搜狗细胞词库下载沪深A股上市公司名单，并添加至自定义词库
dictpath="./沪深A股上市公司名单.txt"
#添加停用词
stoppath="./stopwords.txt"
#初始化分词器
cutter = worker(bylines = TRUE,stop_word=stoppath,user = dictpath) 
res_stop = cutter[contents] 
head(res_stop,1)


####提取高频词
####进行词频统计
freq = as.data.frame(table(unlist(res_stop)),stringsAsFactors = F) 
####按词频个数降序排列           
freq = freq[order(freq[,2],decreasing = TRUE),]  
####挑选前50个高频词                                
top50 = freq[1:50,]
colnames(top50)=c('text','Freq')
top50
```

可以看到年、月、日出现频率很高，但在文本分析中意义不大，故删去

# 过滤“年”、“月”、“日”

```{r}
##在上面的过滤基础上，利用filter_segment()继续过滤掉“年”、“月”、“日”三个词：
filter<-c("年","月","日")
res_stop<-filter_segment(res_stop,filter)
head(res_stop,1)
```

```{r}
####再次提取高频词
####进行词频统计
freq_new = as.data.frame(table(unlist(res_stop)),stringsAsFactors = F) 
####按词频个数降序排列           
freq_new = freq_new[order(freq_new[,2],decreasing = TRUE),]  
####挑选前50个高频词                                
top50_new = freq_new[1:50,]
colnames(top50_new)=c('text','Freq')
top50_new
```



# 绘制词云图

```{r}
####制作词云图
library(wordcloud2)
wordcloud2(top50_new,size=0.5)

```


# 词性提取

```{r}
library(dplyr)
library(tibble)
###词性提取
#构筑词性标注环境
seg <- worker('tag',stop_word=stoppath,user=dictpath)
#对所有的新闻进行中文分词
seg_contents = segment(contents,seg) 
#显示新闻中前15个的词语及其词性
head(seg_contents)
#将数据存储为tibble数据框,转换为具有名称和值的数据框
seg_table <- enframe(seg_contents)
#显示前15个
head(seg_table,15)



##利用filter函数筛选名词(也可以筛选其他词性，此处以名词n为例)
n_seg <- seg_table %>% 
  select(name,value)%>% 
  filter(name == "n")

head(n_seg,15)
```












